### ISSUE TITLE
IE9 should work

### ISSUE THREAD

**Issue by tilgovi** [necolas/dom-matches#2]
http://caniuse.com/#feat=matchesselector

**Comment by tilgovi** [comment]
If that's the case, you can update your compat listing at the bottom.

**Comment by necolas** [comment]
Complete IE9 support (matching orphans) was removed: https://github.com/necolas/dom-matches/commit/b68abd2b117da8cda9922c4f6b6b1b1f98c27958

**Comment by tilgovi** [comment]
So it should work as long as the element is attached to the document?

**Comment by necolas** [comment]
yes i think so
